version: '3'
services:
    db:
        image: 'postgres:13.3'
        ports:
            - '5432:5432'
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: vulpix_prod
    app:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        ports:
            - '5000:5000'
        environment:
            DB_HOST: db
            DATABASE_URL: postgres://postgres:postgres@db:5432/vulpix_prod
            GMAIL_PASSWORD: ${GMAIL_PASSWORD}
            FRONTEND_URL: ${FRONTEND_URL}
